#!/usr/bin/env bash

set -o monitor   # for job control.

R="\e[31m"       # red
G="\e[32m"       # green
Y="\e[33m"       # yellow
B="\e[34m"       # blue
N="\e[0m"        # no color

# Defaults
DIR=$PWD
HOST='localhost'
PORT=8000

http_print_help() {
cat <<EOF
Run Python 3 HTTP Server.

Usage:
    http [OPTIONS]... [ARGS]...

Options:
    -c, --cgi       run HTTP Server as CGI Server.
    -l, --local     bind to localhost (default)
    -b, --bind      specify host to bind
    -d, --dir       specify directory to serve. CWD by default.
    -f, --firefox   run Firefox.
    -h, --help      print this message and exit.

Just run 'http' to serve current working directory at
http://localhost:8000/
Or 'http 1234' to run HTTP server on port 1234.

TODO:
dynamic port change if port is already in use by another process.
EOF
exit 0
}

http_parse_binding() {
    if [ "$(grep -o : <<<"$1")" ]
    then
        HOST="$(echo "$1" | cut -d ":" -f 1)"
        PORT="$(echo "$1" | cut -d ":" -f 2)"
    else
        HOST="$1"
        if [ "$2" ] && [ ${2:0:1} != "-" ]
        then
            PORT="$2"
        fi
    fi
}

while (( "$#" ))
do
    case "$1" in
        -c|--cgi)
            CGI='--cgi';;
        -l|--local|localhost)
            HOST='localhost';;
        -b|--bind)
            if [ "$2" ] && [ ${2:0:1} != "-" ]
            then
                http_parse_binding "$2" "$3"
                shift
            else
                echo -e "${R}$0: Error: Cannot bind to $2${N}"
                echo -e "${Y}Binding to localhost...${N}"
                HOST='localhost'
            fi
            ;;
        -d|--dir)
            if [ -d "$2" ]
            then
                DIR="$2"
                shift
            else
                echo -e "${R}$0: Error: Bad directory: $2${N}"
                exit 1
            fi
            ;;
        -f|--firefox)
            FOX=1;;
        -h|--help)
            http_print_help;;
        -*|--*) echo -e "${R}$0: Error: Bad option: $1${N}";;
        *) PORT="$1";;
    esac
    shift
done

if [[ $( python3 -V | egrep -o "[[:digit:]]" | head -1 ) == '3' ]]
then
    echo -e "Serve: $DIR\t${Y}Press ^C to stop serving.${N}"
    python3 -m http.server $CGI --bind $HOST $PORT --directory $DIR &
    [[ "$FOX" == 1 ]] && firefox http://localhost:$PORT/
    fg
else
    echo -e "${R}$0: Error: Python 3 is not available${N}"
fi
